import type { BotState } from "./types";
import { getWeekKey } from "./utils";

export const initialBots: Record<"phar" | "aero", BotState> = {
  phar: {
    id: "phar",
    sym: "PHAR",
    price: 186.94,
    active: true,
    trailing: true,
    expansion: true,
    gridType: "arith",
    nLevels: 8,
    low: 131,
    high: 180,
    orderSize: 187.5,
    budget: 1500,
    held: 0,
    invested: 0,
    fills: new Set(),
    extraLevels: [],
    change: -1.2,
    atr: 4.2,
    priceHi: 195,
    priceLo: 128,
    zoneFilter: true,
    rsiThreshold: 45,
    maFilter: true,
    rsi: 50,
    ma20: 0,
    priceHistory: [],
    scalping: false,
    scalpPct: 3,
    scalpQty: 50,
    scalpTargets: [],
    scalpProfit: 0,
    dailyLimit: 500,
    weeklyLimit: 0,
    dailySpent: 0,
    weeklySpent: 0,
    lastDayReset: new Date().toDateString(),
    lastWeekReset: getWeekKey(),
    minInterval: 0,
    lastFillTime: 0,
    rangeDepthIdx: 2,
  },
  aero: {
    id: "aero",
    sym: "AERO",
    price: 0.34,
    active: true,
    trailing: true,
    expansion: true,
    gridType: "arith",
    nLevels: 10,
    low: 0.11,
    high: 0.31,
    orderSize: 200,
    budget: 2000,
    held: 0,
    invested: 0,
    fills: new Set(),
    extraLevels: [],
    change: -3.1,
    atr: 8.7,
    priceHi: 0.365,
    priceLo: 0.095,
    zoneFilter: true,
    rsiThreshold: 45,
    maFilter: true,
    rsi: 50,
    ma20: 0,
    priceHistory: [],
    scalping: false,
    scalpPct: 3,
    scalpQty: 50,
    scalpTargets: [],
    scalpProfit: 0,
    dailyLimit: 500,
    weeklyLimit: 0,
    dailySpent: 0,
    weeklySpent: 0,
    lastDayReset: new Date().toDateString(),
    lastWeekReset: getWeekKey(),
    minInterval: 0,
    lastFillTime: 0,
    rangeDepthIdx: 3,
  },
};
